version: "3"
services:
  xeditmirror:
    container_name: xeditmirror
    image: xeditmirror
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DOWNLOAD_PATH=/downloads
      - CHECK_INTERVAL=86400
    env_file:
      - stack.env
    volumes:
      - /home/isaac/Media/Host/files/xEditMirror:/downloads